### ISSUE TITLE
strtolower of string months has side effects on other Translations

### ISSUE THREAD

**Issue by Kathrin84** [marinaglancy/moodle-format_periods#1]
Hi Marina,

we installed your course format and contributed a german translation.

I was wondering if I made a typo in the translation because in the dropdown field the options are displayed correct except for the option 'months'.
This string is displayed in lower case, but should begin with a capital letter, too.

![probs_in_lang_de](https://cloud.githubusercontent.com/assets/4711883/7318218/b063a942-ea89-11e4-9b6b-235d4bba78ca.png)

As I didn't find the string in your language pack, I did some code research and found out that you added a strtolower to solely the month string in periodduration.php:

![periodduration_php](https://cloud.githubusercontent.com/assets/4711883/7318314/d702868a-ea8a-11e4-92a5-836367a005b7.png)

I wondered why you did this and I had a look at the language pack and found out that the naming convention there is not consistent. Days, weeks and years are written in lower case and only month is written with a capital letter:
![lang_core_days](https://cloud.githubusercontent.com/assets/4711883/7318271/4cdc5fa8-ea8a-11e4-9e54-1606f8331113.png)
![lang_core_weeks](https://cloud.githubusercontent.com/assets/4711883/7318272/4cfa733a-ea8a-11e4-847d-daaa3b8eefa8.png)
![lang_core_months](https://cloud.githubusercontent.com/assets/4711883/7318323/eb9a42ea-ea8a-11e4-815d-23d5838991e1.png)
![lang_core_years](https://cloud.githubusercontent.com/assets/4711883/7318273/4cfe4492-ea8a-11e4-932a-05d914749673.png)

So, would you please delete the strtolower in your code so that other languages can display their strings in their correct way.
As you probably have a closer contact to the english language maintainers, you could make a suggestion to name the date labels in a consistent way.

Best regards
Kathrin

**Comment by Kathrin84** [comment]
I assume that you have a lot of work at the HQ, nevertheless I wanted to leave a short reminder for this issue. :)

**Comment by wildgirl** [comment]
Hi Kathrin,
Thanks for pointing out this consistency issue with language string capitalization. As it's a core issue, I have created a tracker issue for it: https://tracker.moodle.org/browse/MDL-50752.

**Comment by marinaglancy** [comment]
I resolved it with the same strings that Davo used in #2
