### ISSUE TITLE
Format periods does not add sections to the new flat navigation in theme Boost when setting "Show all periods on one page" is set

### ISSUE THREAD

**Issue by Kathrin84** [marinaglancy/moodle-format_periods#8]
Hi Marina,

at the moment we're testing our instance for Moodle 3.2 with theme Boost, respectively with an own child theme of Boost.

We encountered, that your course format does not add the sections as menu items to the new flat navigation when the setting "Show all periods on one page" ist active. The core formats like Topics and Weeks do add the sections to the flat navigation as menu items when the equivalent setting "show all sections on one page" is active.

Do you think that it's possible that you could extend your plugin in that direction? This would be great because the fast access to all available sections in the menu is a very good feature and then the user's expectation will also be satisfied with same behaviour like the core course formats have.

Best regards,
Kathrin

**Comment by abias** [comment]
Hi Marina,

I dug slightly into this issue and found that your function get_view_url() in lib.php differs from format_topic's lib.php in Moodle 3.2 at a crucial point.

If I apply this patch to your plugin:

```
diff --git a/course/format/periods/lib.php b/course/format/periods/lib.php
index 8ea9618..0b41b7f 100644
--- a/course/format/periods/lib.php
+++ b/course/format/periods/lib.php
@@ -139,9 +139,6 @@ class format_periods extends format_base {
             if ($sectionno != 0 && $displaymode == COURSE_DISPLAY_MULTIPAGE) {
                 $url->param('section', $sectionno);
             } else {
-                if (!empty($options['navigation'])) {
-                    return null;
-                }
                 $url->set_anchor('section-'.$sectionno);
             }
         }

```
the sections are always added to Boost's flat navigation just as format_topic does and just as a user would expect it with Boost.

I would appreciate if you could find the time to adopt this change from format_topics into your 3.2 version of format_periods or make the behaviour at least configurable for admins.

Please also note that there is a general discussion going on about this topic on https://tracker.moodle.org/browse/MDL-57412.

Thanks,
Alex

**Comment by abias** [comment]
Hi Marina,

I saw that you published a new 3.3-only version of this plugin and have removed the 3 lines which I indicated above. 

I assume that you won't solve this problem anymore for the 3.2 version. So you probably can close this ticket.

Thanks,
Alex

**Comment by marinaglancy** [comment]
Thanks Alexander,
I still maintain 3.2 so I will pull that in the new version. Thanks!

**Comment by marinaglancy** [comment]
I updated both releases: v3.0.5 for Moodle 3.0-3.2
and v3.1.2 for Moodle 3.3-3.4

Now I respect $CFG->linkcoursesections same way it was decided in https://tracker.moodle.org/browse/MDL-57412
